require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
	Pry.start
end

desc "Greet everyone"
task :greet do
	puts "Hello World"
end
